<?php

namespace Ams\DistributionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BordereauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BordereauRepository extends EntityRepository {

    public function getBordereau($oDepot, $date, $flux) {
        $sql = "select bord.point_livraison as PL,mtj.code as code_tournee from client_a_servir_logist casl
                join depot dep ON dep.id = casl.depot_id
                inner join modele_tournee_jour mtj ON mtj.id = casl.tournee_jour_id
                join bordereau bord ON bord.point_livraison=casl.point_livraison_id
                where casl.date_parution= '" . $date . "' AND casl.flux_id = $flux";
        if ($oDepot) {
            $sql.= " AND dep.id=" . $oDepot->getId() . " ";
        }else{
            $sql.= " AND dep.id is NULL ";
        }
        $sql.=" GROUP BY bord.point_livraison,mtj.code ORDER BY mtj.code ASC ,casl.point_livraison_ordre";
        
        return $this->_em->getConnection()->fetchAll($sql);
    }

}
