<?php

namespace Ams\DistributionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FranceRoutageTraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranceRoutageTraitementRepository extends EntityRepository
{
     public function waitingFiles() {
        $connection = $this->getEntityManager()->getConnection();
        $q =    "
                SELECT 
                    frt . *
                FROM
                    (SELECT 
                        *, MAX(id) as max_id
                    FROM
                        france_routage_traitement
                    WHERE
                        date_fin_traitement is null
                        AND date_annulation is null
                    GROUP BY code_societe , date_parution) as france_routage
                        JOIN
                    france_routage_traitement frt ON frt.id = france_routage.max_id
        ";
        $stmt = $connection->executeQuery($q);
        return $stmt->fetchAll();
    }     

    public function cancelFilesAuto() {
        $connection = $this->getEntityManager()->getConnection();
        $q =    "
                SELECT * from france_routage_traitement
                WHERE succes = 0
                    AND date_annulation is not null
                    AND is_read is null
        ";
        $stmt = $connection->executeQuery($q);
        return $stmt->fetchAll();
    }    

    public function activeFilesAuto() {
        $connection = $this->getEntityManager()->getConnection();
        $q =    "
                  SELECT 
                    frt . *
                    FROM
                        (SELECT 
                            *, MAX(id) as max_id
                        FROM
                            france_routage_traitement
                        GROUP BY code_societe , nom_fichier , repertoire_ftp_source) as france_routage
                            JOIN
                    france_routage_traitement frt ON frt.id = france_routage.max_id
                ";
        $stmt = $connection->executeQuery($q);
        return $stmt->fetchAll();
    }
}
