<?php

namespace Ams\DistributionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FranceRoutageTraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranceRoutageProspectionListeRepository extends EntityRepository
{
    public function waitingFiles($date) {
        $connection = $this->getEntityManager()->getConnection();
        $q =    "
                SELECT frpl.*, s.libelle as soc_libelle, s.code as soc_code
                FROM france_routage_prospection_liste frpl , societe s
                WHERE s.id = frpl.societe_id
                AND date_commande > '$date'
        ";
        $stmt = $connection->executeQuery($q);
        return $stmt->fetchAll();
    }
    
    public function exportCsv(){
        
        $q = "  SELECT *
                FROM france_routage_prospection
                ";
        $lignes = $this->_em->getConnection()->executeQuery($q);
        
        
        $chemin = 'fichier.csv';
        
        $fichier_csv = fopen($chemin, 'w+');
        
        fprintf($fichier_csv, chr(0xEF).chr(0xBB).chr(0xBF));
        
        foreach($lignes as $ligne){
            fwrite($fichier_csv, utf8_decode(implode('|', $ligne))."\n");
        }
        
        fclose($fichier_csv);
    }
    
    public function setEtat($etatId, $id){
        $Update = " UPDATE france_routage_prospection_liste
                            SET etat_id = $etatId
                            WHERE id = $id
                            ";
        $this->_em->getConnection()->executeQuery($Update);
    }
}
