<?php

namespace Ams\DistributionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InfoPortageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoPortageRepository extends EntityRepository
{

    public function getInfoPortageLivraisonByAboSoc($aboSoc) {
        $q=
           "
            SELECT ip.*,tip.libelle as typeInfoPortage from infos_portages_livraisons 
                JOIN adresse a ON a.point_livraison_id = livraison_id
                JOIN info_portage ip ON ip.id = info_portage_id AND curdate() BETWEEN ip.date_debut AND ip.date_fin 
                JOIN type_info_portage tip ON tip.id = type_info_id
            WHERE abonne_soc_id = $aboSoc 
                AND curdate() BETWEEN a.date_debut AND a.date_fin ;
           ";
        return $this->_em->getConnection()->fetchAll($q);
    }
    
    
    
        
    /**
     * Desactive tous les infos portage
     * dont les dates de fin sont dépassees
     */
    public function  desactiveInfoPortage () {
        try {
            $sql = " UPDATE  info_portage set active = 0 WHERE date_fin < NOW() ";
            $this->_em->getConnection()->prepare($sql)->execute();
        } catch (DBALException $ex) {
            throw $ex;
        }  
    }
}
