<?php

namespace Ams\DistributionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JourFerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourFerieRepository extends EntityRepository
{
    public function getCalendrierEmploye($employe_id,$flux_id,$depot_id){
        
        
    }
    
    public function getJourFerie(){
            
    }
}
