<?php

namespace Ams\DistributionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OuvertureCdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OuvertureCdRepository extends EntityRepository
{
    
    public function getListeFiltree($date) {

        $sql = "SELECT *, DATE_FORMAT(heure_ouverture, '%H:%i:%s') as new_date
            FROM  
                ouverture_centre
            INNER JOIN
                depot ON ouverture_centre.depot_id = depot.id
            WHERE 
                DATE(heure_ouverture) = '" . $date . "'";
            
       
        return $this->_em->getConnection()->fetchAll($sql);
    }
    
    public function isNew($param, $date) {

        $sql = "SELECT *
            FROM  
                ouverture_centre
            WHERE 
                DATE(heure_ouverture) = '" . $date . "' AND depot_id = '".$param."'";
            
        return $this->_em->getConnection()->fetchAll($sql);
    }
   
}
