<?php

namespace Ams\DistributionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResultatDistributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatDistributionRepository extends EntityRepository
{
    public function checkEnregistrements($produitId, $depotId, $dateDistrib) {
        
        
        $sql = "SELECT *
            FROM  
                resultat_distribution
            WHERE 
                depot_id LIKE ".$depotId."
            AND
                produit_id LIKE ".$produitId."
            AND
                date_distribution LIKE '".$dateDistrib->format('Y-m-d')."'";
            
       
        return $this->_em->getConnection()->fetchAll($sql);
    }
}
