<?php

namespace Ams\DistributionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FranceRoutageScriptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranceRoutageScriptRepository extends EntityRepository
{
}
