imports:
    - { resource: parameters_test.yml }
    - { resource: config.yml }
    - { resource: mroad_test.ini }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

fire_php: ~

#assetic:
#    use_controller: false

#swiftmailer:
#    delivery_address: me@example.com


#twig:
#    globals:
#        param: "@param"
        
        
        