imports:
    - { resource: parameters_preprod.yml }
    - { resource: config.yml }
    - { resource: mroad_preprod.ini }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        chromephp:
            type:  chromephp
            level: info
fire_php: ~