parameters:
    database_driver: pdo_mysql
    database_host: py-ch-devwebapp2.adonis.mediapole.info
    database_port: null
    database_name: silog
    database_user: silog
    database_password: xnVsAD
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: a4e099cd15a136f048d2df6bec0597b1a1252284
    database_path: null

#Connection Pleiades
    database_driver_ple: oci8
    database_host_ple: '10.216.5.20'
    database_port_ple: '1525'
    database_name_ple: PNG
    database_service_ple:  true
    database_user_ple: PNG3_MOD
    database_password_ple: ADMINPNG3_MOD
    database_charset_ple: AL32UTF8

#Connection Octime
    database_driver_oc: oci8
    database_host_oc: '10.216.5.20'
    database_port_oc: '1525'
    database_name_oc: POCT
    database_service_oc:  true
    database_user_oc: sdv
    database_password_oc: adminsdv
    database_charset_oc: AL32UTF8
    
#WebService GEOCODAGE : Criteres de qualification (OK | A_STATUER | AUCUNE_PROPOSITION) & options d'appel de SOAP     
    GEOC_WS_GEOCODE_SOAP_CRITERIA_OK: 
        - { GeocodeType: 4, GeocodeScoreMin: 14 }
        - { GeocodeType: 3, GeocodeScoreMin: 14 }
    # Comme projection, on peut utiliser "MAP" [Lambert II etendu] (expl : X=607439 , Y:2403317 ) 
    # ou "EPSG:27572" (expl : X=607439.257 , Y:2403317.08)
    # ou "WGS84" [Système geodesique standard mondial, notamment utilise par le systeme GPS] ( X=2.437402 , Y=48.628449)
    # projectionGeocodage: "EPSG:27572" 
    #projectionGeocodage: "WGS84" 
    GEOC_WS_GEOCODE_SOAP_OPTION: { connection_timeout: 5000, cache_wsdl: 3, encoding: "UTF-8" }
    #GEOC_WS_GEOCODE_SOAP_OPTION: { connection_timeout: 5000, cache_wsdl: 3, proxy_host: "10.196.20.193", proxy_port: "80", encoding: "UTF-8" }
    # 'cache_wsdl' => WSDL_CACHE_BOTH ..... WSDL_CACHE_BOTH correspond a 3

