<?php

namespace Ams\AdresseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DepotCommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotCommuneRepository extends EntityRepository
{
    public function getCommunesBetweenDate($commune, $date)
    {
        $qb = $this->createQueryBuilder('DC');
        $qb ->leftJoin('DC.depot', 'D')
            ->where('DC.commune = :commune')
            ->andWhere(
                $qb->expr()->between(':dateFind', 'DC.dateDebut', 'DC.dateFin')
            )
            ->setParameter(":commune", $commune)
            ->setParameter(":dateFind", $date)
            ->addSelect('DC')
            ->addSelect('D')
        ;
        
        return $qb->getQuery()->getResult();
    }
}
