<?php

namespace Ams\DistributionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DepotCommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeRepository extends EntityRepository
{
   /**
    * 
    * @param type $depotId
    * @param type $fluxId
    * @return array employe
    */
    public  function getEmployeByDepotAndFlux($depotId, $fluxId) {
        $sql = " SELECT 
                  E.id, CONCAT_WS(' ', E.prenom1, E.prenom2, E.nom) nom_prenom 
                 FROM employe E
                 LEFT JOIN emp_pop_depot EPD ON E.id = EPD.employe_id
                 WHERE EPD.depot_id =".$depotId." AND EPD.flux_id =".$fluxId
                 ." AND NOW() between  EPD.date_debut AND EPD.date_fin  ";  
        
         return $this->_em->getConnection()->fetchAll($sql);
    }
}
