<?php

namespace Ams\AdresseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TourneeStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourneeStatsRepository extends EntityRepository
{
    public function insert($date,$code,$data)
    {

        $aData = array('stats' => $data);
        $q = " 
              INSERT INTO tournee_stats
              VALUES('$code','$date',:stats)
            ";
        $this->_em->getConnection()->executeQuery($q,$aData);
    }
    
    public function update($date,$code,$data)
    {
        $aData = array('stats' => $data);
        $q = " 
              UPDATE tournee_stats
              SET stats = :stats
              WHERE tournee_jour_code = '$code'
                AND date_distrib = '$date'
            ";
        $this->_em->getConnection()->executeQuery($q,$aData);
    }
    
    public function exist($date,$code)
    {
        $connection = $this->getEntityManager()->getConnection();
        $q = " 
            SELECT * FROM tournee_stats
            WHERE tournee_jour_code = '$code'
                AND date_distrib = '$date'
            ";
        return $connection->executeQuery($q)->fetch();
    }
}
