<?php

namespace Ams\ProduitBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitAdditionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitAdditionnelRepository extends EntityRepository
{
}
