drop TABLE `emp_contrat_hp`;
CREATE TABLE `emp_contrat_hp` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `employe_id` int(11) NOT NULL,
  `depot_id` int(11) DEFAULT NULL,
  `flux_id` int(11) DEFAULT NULL,
  `activite_id` int(11) DEFAULT NULL,
  `date_debut` date NOT NULL,
  `date_fin` date NOT NULL,
  `lundi` tinyint(1) NOT NULL,
  `mardi` tinyint(1) NOT NULL,
  `mercredi` tinyint(1) NOT NULL,
  `jeudi` tinyint(1) NOT NULL,
  `vendredi` tinyint(1) NOT NULL,
  `samedi` tinyint(1) NOT NULL,
  `dimanche` tinyint(1) NOT NULL,
  `heure_debut` time DEFAULT NULL,
  `nbheures_jour` decimal(5,2) NOT NULL DEFAULT '0.00',
  `nbheures_mensuel` decimal(5,2) NOT NULL DEFAULT '0.00',
  `travhorspresse` varchar(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `commentaire` varchar(1024) COLLATE utf8_unicode_ci DEFAULT NULL,
  `date_creation` datetime NOT NULL,
  `date_modif` datetime DEFAULT NULL,
  `utilisateur_id` int(11) NOT NULL,
  `oid` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `rcoid` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `ordre` decimal(2,0) DEFAULT NULL,
  `xta_rcactivte` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `xta_rcmetier` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  `xta_rcactivhpre` varchar(36) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ak_emp_contrat_hp` (`rcoid`,`ordre`,`date_debut`),
--  KEY `fk_emp_contrat_hp_012` (`xta_rcactivte`),
--  KEY `fk_emp_contrat_hp_013` (`xta_rcmetier`),
--  KEY `fk_emp_contrat_hp_017` (`xta_rcactivhpre`),
  KEY `fk_emp_contrat_hp_depot_id` (`depot_id`),
  KEY `fk_emp_contrat_hp_flux_id` (`flux_id`),
  KEY `fk_emp_contrat_hp_activite_id` (`activite_id`),
  KEY `emp_contrat_hp_idx` (`rcoid`,`date_debut`,`date_fin`),
  KEY `emp_contrat_hp_idx2` (`utilisateur_id`),
--  CONSTRAINT `fk_emp_contrat_hp_012` FOREIGN KEY (`xta_rcactivte`) REFERENCES `pai_png_xta_rcactivite` (`oid`) ON DELETE NO ACTION ON UPDATE NO ACTION,
--  CONSTRAINT `fk_emp_contrat_hp_013` FOREIGN KEY (`xta_rcmetier`) REFERENCES `pai_png_xta_rcmetier` (`oid`) ON DELETE NO ACTION ON UPDATE NO ACTION,
--  CONSTRAINT `fk_emp_contrat_hp_017` FOREIGN KEY (`xta_rcactivhpre`) REFERENCES `pai_png_xta_rcactivhpre` (`oid`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_contrat_hp_activite_id` FOREIGN KEY (`activite_id`) REFERENCES `ref_activite` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_contrat_hp_depot_id` FOREIGN KEY (`depot_id`) REFERENCES `depot` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_contrat_hp_flux_id` FOREIGN KEY (`flux_id`) REFERENCES `ref_flux` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_contrat_hp_utilisateur_id` FOREIGN KEY (`utilisateur_id`) REFERENCES `utilisateur` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

