parameters:
#    ams_invendu.example.class: Ams\InvenduBundle\Example

services:
#    ams_invendu.example:
#        class: %ams_invendu.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
