suivi_cron_vue_generale:
    pattern:  /suivi-cron-liste
    defaults: { _controller: "AmsExploitationBundle:SuiviCron:list" }

suivi_cron_vue_generale_xml:
    pattern:  /suivi-cron-xml
    defaults: { _controller: "AmsExploitationBundle:SuiviCron:grid" }
    
suivi_cron_log_file:
    pattern: /suivi-cron-file/{cronId}/{logName}
    defaults: { _controller: "AmsExploitationBundle:SuiviCron:download" }