parameters:
#    ams_referentiel.example.class: Ams\ReferentielBundle\Example

services:
#    ams_referentiel.example:
#        class: %ams_referentiel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
