<?php

namespace Ams\SilogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsRepository extends EntityRepository
{
    public function insert($userId,$task,$path,$date,$comment = false) {
    $sql = '
            INSERT INTO documents (user,task,path,date,commentaire)
            VALUES ('.$userId.',"'.$task.'","'.$path.'","'.$date.'","'.$comment.'")
           ';

    return $this->_em->getConnection()->prepare($sql)->execute();
    }
}
