<?php

namespace Ams\SilogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessagesInfosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessagesInfosRepository extends EntityRepository
{
}
