<?php

namespace Ams\SilogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TmpSrcDetailsCasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TmpSrcDetailsCasRepository extends EntityRepository
{
}
