<?php

namespace Ams\SilogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TraceUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraceUserRepository extends EntityRepository
{


    public function newConnection($aData) {
        $q ="
               INSERT INTO trace_user (id_user,connect_time,browser,ip_address)
               VALUES(".$aData['id_user'].",'".$aData['connect_time']."','".$aData['browser']."','".$aData['ip_address']."')
            ";

        $this->_em->getConnection()->prepare($q)->execute();
    }
}


