DROP TABLE pai_ref_insee_pays;
CREATE TABLE pai_ref_insee_pays(
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  code varchar(3) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  pays varchar(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  capital varchar(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  nationalite varchar(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  iso2 varchar(2) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  iso3 varchar(3) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  ue_ varchar(1) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' DEFAULT 'N' NOT NULL, 
  eee_ varchar(1) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' DEFAULT 'N' NOT NULL, 
  ue TINYINT(1) DEFAULT 0 NOT NULL, 
  eee TINYINT(1) DEFAULT 0 NOT NULL, 
  UNIQUE INDEX pai_pai_ref_insee_pays_uk (`code` ASC),
  CONSTRAINT pai_pai_ref_insee_pays_pk PRIMARY KEY (id)
  )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

update pai_ref_insee_pays set ue=1 where ue_='O';
update pai_ref_insee_pays set eee=1 where eee_='O';
select * from pai_ref_insee_pays where ue=1;
select * from pai_ref_insee_pays where eee=1;
select * from pai_ref_insee_pays;
alter table pai_ref_insee_pays drop eee_;
alter table pai_ref_insee_pays drop ue_;
   
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('319','ACORES, MADERE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('212','AFGHANISTAN',null,null,'AF','AFG','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('303','AFRIQUE DU SUD',null,null,'ZA','ZAF','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('404','ALASKA',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('125','ALBANIE','TIRANA',null,'AL','ALB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('352','ALGERIE','ALGER','ALGERIENNE','DZ','DZA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('109','ALLEMAGNE','BERLIN',null,'DE','DEU','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('130','ANDORRE',null,null,'AD','AND','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('395','ANGOLA',null,null,'AO','AGO','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('425','ANGUILLA',null,null,'AI','AIA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('441','ANTIGUA-ET-BARBUDA',null,null,'AG','ATG','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('431','ANTILLES NEERLANDAISES',null,null,'AN',null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('201','ARABIE SAOUDITE',null,null,'SA','SAU','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('415','ARGENTINE',null,null,'AR','ARG','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('252','ARMENIE',null,null,'AM','ARM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('501','AUSTRALIE',null,null,'AU','AUS','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('110','AUTRICHE',null,null,'AT','AUT','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('253','AZERBAIDJAN',null,null,'AZ','AZE','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('436','BAHAMAS',null,null,'BS','BHS','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('249','BAHREIN',null,null,'BH','BHR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('246','BANGLADESH',null,null,'BD','BGD','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('434','BARBADE',null,null,'BB','BRB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('131','BELGIQUE',null,null,'BE','BEL','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('429','BELIZE',null,null,'BZ','BLZ','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('327','BENIN',null,null,'BJ','BEN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('214','BHOUTAN',null,null,'BT','BTN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('148','BIELORUSSIE',null,null,'BY','BLR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('224','BIRMANIE',null,null,'MM','MMR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('418','BOLIVIE',null,null,'BO','BOL','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('118','BOSNIE-HERZEGOVINE',null,null,'BA','BIH','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('347','BOTSWANA',null,null,'BW','BWA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('103','BOUVET (ILE)',null,null,'BV','BVT','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('416','BRESIL',null,null,'BR','BRA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('225','BRUNEI',null,null,'BN','BRN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('111','BULGARIE',null,null,'BG','BGR','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('331','BURKINA',null,null,'BF','BFA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('321','BURUNDI',null,null,'BI','BDI','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('234','CAMBODGE',null,null,'KH','KHM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('322','CAMEROUN','YAOUNDE','CAMEROUNAISE','CM','CMR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('305','CAMEROUN ET TOGO',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('401','CANADA',null,null,'CA','CAN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('313','CANARIES (ILES)',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('396','CAP-VERT',null,null,'CV','CPV','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('323','CENTRAFRICAINE (REPUBLIQUE)',null,null,'CF','CAF','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('417','CHILI',null,null,'CL','CHL','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('216','CHINE',null,null,'CN','CHN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('254','CHYPRE',null,null,'CY','CYP','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('419','COLOMBIE',null,null,'CO','COL','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('397','COMORES',null,null,'KM','COM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('324','CONGO',null,null,'CG','COG','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('312','CONGO (REPUBLIQUE DEMOCRATIQUE)',null,null,'CD','COD','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('502','COOK (ILES)',null,null,'CK','COK','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('237','COREE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('239','COREE (REPUBLIQUE DE)',null,null,'KR','KOR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('238','COREE (REPUBLIQUE POPULAIRE DEMOCRATIQUE DE)',null,null,'KP','PRK','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('406','COSTA RICA',null,null,'CR','CRI','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('326','COTE D''IVOIRE','ABIDJAN',null,'CI','CIV','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('119','CROATIE',null,null,'HR','HRV','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('407','CUBA',null,null,'CU','CUB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('101','DANEMARK',null,null,'DK','DNK','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('399','DJIBOUTI',null,null,'DJ','DJI','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('408','DOMINICAINE (REPUBLIQUE)',null,null,'DO','DOM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('438','DOMINIQUE',null,null,'DM','DMA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('301','EGYPTE',null,null,'EG','EGY','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('414','EL SALVADOR',null,null,'SV','SLV','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('247','EMIRATS ARABES UNIS',null,null,'AE','ARE','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('420','EQUATEUR',null,null,'EC','ECU','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('317','ERYTHREE',null,null,'ER','ERI','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('134','ESPAGNE',null,null,'ES','ESP','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('106','ESTONIE',null,null,'EE','EST','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('228','ETATS MALAIS NON FEDERES',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('315','ETHIOPIE',null,null,'ET','ETH','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('156','EX-REPUBLIQUE YOUGOSLAVE DE MACEDOINE',null,null,'MK','MKD','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('508','FIDJI',null,null,'FJ','FJI','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('105','FINLANDE',null,null,'FI','FIN','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('000','FRANCE','PARIS','FRANCAISE','FR','FRA','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('328','GABON',null,null,'GA','GAB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('304','GAMBIE',null,null,'GM','GMB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('255','GEORGIE',null,null,'GE','GEO','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('329','GHANA',null,null,'GH','GHA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('133','GIBRALTAR',null,null,'GI','GIB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('126','GRECE',null,null,'GR','GRC','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('435','GRENADE',null,null,'GD','GRD','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('430','GROENLAND',null,null,'GL','GRL','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('505','GUAM',null,null,'GU','GUM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('409','GUATEMALA',null,null,'GT','GTM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('330','GUINEE',null,null,'GN','GIN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('314','GUINEE EQUATORIALE',null,null,'GQ','GNQ','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('392','GUINEE-BISSAU',null,null,'GW','GNB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('428','GUYANA',null,null,'GY','GUY','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('410','HAITI',null,null,'HT','HTI','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('504','HAWAII (ILES)',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('411','HONDURAS',null,null,'HN','HND','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('230','HONG-KONG',null,null,'HK',null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('112','HONGRIE',null,null,'HU','HUN','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('320','ILES PORTUGAISES DE L''OCEAN INDIEN',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('223','INDES','NEW DELHI','INDIENNE','IN','IND','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('231','INDONESIE',null,null,'ID','IDN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('204','IRAN','TEHERAN','IRANIENNE','IR','IRN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('203','IRAQ',null,null,'IQ','IRQ','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('136','IRLANDE, ou EIRE',null,null,'IE','IRL','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('102','ISLANDE',null,null,'IS','ISL','N','O');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('207','ISRAEL',null,null,'IL','ISR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('127','ITALIE',null,null,'IT','ITA','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('426','JAMAIQUE',null,null,'JM','JAM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('217','JAPON',null,null,'JP','JPN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('222','JORDANIE',null,null,'JO','JOR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('211','KAMTCHATKA',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('256','KAZAKHSTAN',null,null,'KZ','KAZ','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('332','KENYA',null,null,'KE','KEN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('257','KIRGHIZISTAN',null,null,'KG','KGZ','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('513','KIRIBATI',null,null,'KI','KIR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('240','KOWEIT',null,null,'KW','KWT','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('403','LABRADOR',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('241','LAOS',null,null,'LA','LAO','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('348','LESOTHO',null,null,'LS','LSO','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('107','LETTONIE',null,null,'LV','LVA','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('205','LIBAN',null,null,'LB','LBN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('302','LIBERIA',null,null,'LR','LBR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('316','LIBYE',null,null,'LY','LBY','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('113','LIECHTENSTEIN',null,null,'LI','LIE','N','O');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('108','LITUANIE',null,null,'LT','LTU','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('137','LUXEMBOURG',null,null,'LU','LUX','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('232','MACAO',null,null,'MO',null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('333','MADAGASCAR','TANANARIVE',null,'MG','MDG','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('227','MALAISIE',null,null,'MY','MYS','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('334','MALAWI',null,null,'MW','MWI','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('229','MALDIVES',null,null,'MV','MDV','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('335','MALI','BAMAKO',null,'ML','MLI','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('427','MALOUINES, OU FALKLAND (ILES)',null,null,'FK','FLK','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('144','MALTE',null,null,'MT','MLT','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('218','MANDCHOURIE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('350','MAROC','RABAT','MAROCAINE','MA','MAR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('515','MARSHALL (ILES)',null,null,'MH','MHL','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('390','MAURICE','PORT LOUIS',null,'MU','MUS','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('336','MAURITANIE','NOUAKCHOTT',null,'MR','MRT','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('405','MEXIQUE',null,null,'MX','MEX','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('516','MICRONESIE (ETATS FEDERES DE)',null,null,'FM','FSM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('151','MOLDAVIE',null,null,'MD','MDA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('138','MONACO',null,null,'MC','MCO','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('242','MONGOLIE',null,null,'MN','MNG','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('120','MONTENEGRO',null,null,'ME','MNE','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('393','MOZAMBIQUE',null,null,'MZ','MOZ','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('311','NAMIBIE',null,null,'NA','NAM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('507','NAURU',null,null,'NR','NRU','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('215','NEPAL',null,null,'NP','NPL','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('412','NICARAGUA',null,null,'NI','NIC','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('337','NIGER',null,null,'NE','NER','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('338','NIGERIA',null,null,'NG','NGA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('578','NORVEGE',null,null,'NO','NOR','N','O');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('308','OCEAN INDIEN (TERRITOIRE BRITANNIQUE DE L'')',null,null,'IO','IOT','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('250','OMAN',null,null,'OM','OMN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('339','OUGANDA',null,null,'UG','UGA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('258','OUZBEKISTAN',null,null,'UZ','UZB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('213','PAKISTAN','ISLAMABAD','PAKISTANAISE','PK','PAK','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('517','PALAOS (ILES)',null,null,'PW','PLW','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('261','PALESTINE','PS','PSE',null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('413','PANAMA',null,null,'PA','PAN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('510','PAPOUASIE-NOUVELLE-GUINEE',null,null,'PG','PNG','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('421','PARAGUAY',null,null,'PY','PRY','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('135','PAYS-BAS',null,null,'NL','NLD','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('422','PEROU',null,null,'PE','PER','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('220','PHILIPPINES',null,null,'PH','PHL','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('503','PITCAIRN (ILE)',null,null,'PN','PCN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('122','POLOGNE','POLONAISE','VARSOVIE','PL','POL','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('432','PORTO RICO',null,null,'PR','PRI','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('139','PORTUGAL','LISBONNE',null,'PT','PRT','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('221','POSSESSIONS BRITANNIQUES AU PROCHE-ORIENT',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('248','QATAR',null,null,'QA','QAT','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('141','REPUBLIQUE DEMOCRATIQUE ALLEMANDE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('142','REPUBLIQUE FEDERALE D''ALLEMAGNE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('114','ROUMANIE',null,null,'RO','ROM','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('132','ROYAUME-UNI',null,null,'GB','GBR','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('123','RUSSIE',null,null,'RU','RUS','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('340','RWANDA',null,null,'RW','RWA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('389','SAHARA OCCIDENTAL',null,null,'EH','ESH','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('442','SAINT-CHRISTOPHE-ET-NIEVES',null,null,'KN','KNA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('306','SAINTE-HELENE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('439','SAINTE-LUCIE',null,null,'LC','LCA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('128','SAINT-MARIN',null,null,'SM','SMR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('440','SAINT-VINCENT-ET-LES GRENADINES',null,null,'VC','VCT','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('512','SALOMON (ILES)',null,null,'SB','SLB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('506','SAMOA OCCIDENTALES',null,null,'WS','WSM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('394','SAO TOME-ET-PRINCIPE',null,null,'ST','STP','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('341','SENEGAL','DAKAR',null,'SN','SEN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('398','SEYCHELLES',null,null,'SC','SYC','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('209','SIBERIE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('342','SIERRA LEONE',null,null,'SL','SLE','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('226','SINGAPOUR',null,null,'SG','SGP','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('117','SLOVAQUIE',null,null,'SK','SVK','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('145','SLOVENIE',null,null,'SI','SVN','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('318','SOMALIE',null,null,'SO','SOM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('343','SOUDAN',null,null,'SD','SDN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('307','SOUDAN ANGLO-EGYPTIEN, KENYA, OUGANDA',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('235','SRI LANKA',null,null,'LK','LKA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('104','SUEDE',null,null,'SE','SWE','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('140','SUISSE',null,null,'CH','CHE','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('437','SURINAME',null,null,'SR','SUR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('391','SWAZILAND',null,null,'SZ','SWZ','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('206','SYRIE',null,null,'SY','SYR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('259','TADJIKISTAN',null,null,'TJ','TJK','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('236','TAIWAN',null,null,'TW','TWN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('325','TANGER',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('309','TANZANIE',null,null,'TZ','TZA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('344','TCHAD',null,null,'TD','TCD','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('115','TCHECOSLOVAQUIE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('116','TCHEQUE (REPUBLIQUE)',null,null,'CZ','CZE','O','0');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('402','TERRE-NEUVE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('219','THAILANDE',null,null,'TH','THA','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('262','TIMOR ORIENTAL',null,null,'TL','TLS','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('345','TOGO',null,null,'TG','TGO','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('509','TONGA',null,null,'TO','TON','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('433','TRINITE-ET-TOBAGO',null,null,'TT','TTO','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('351','TUNISIE','TUNIS','TUNISIENNE','TN','TUN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('210','TURKESTAN RUSSE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('260','TURKMENISTAN',null,null,'TM','TKM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('208','TURQUIE',null,null,'TR','TUR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('124','TURQUIE D''EUROPE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('511','TUVALU',null,null,'TV','TUV','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('155','UKRAINE',null,null,'UA','UKR','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('423','URUGUAY',null,null,'UY','URY','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('514','VANUATU',null,null,'VU','VUT','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('129','VATICAN, ou SAINT-SIEGE',null,null,'VA','VAT','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('424','VENEZUELA',null,null,'VE','VEN','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('243','VIET NAM',null,null,'VN','VNM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('244','VIET NAM DU NORD',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('245','VIET NAM DU SUD',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('251','YEMEN',null,null,'YE','YEM','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('233','YEMEN DEMOCRATIQUE',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('202','YEMEN (REPUBLIQUE ARABE DU)',null,null,null,null,'N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('121','YOUGOSLAVIE',null,null,'MK','MKD','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('346','ZAMBIE',null,null,'ZM','ZMB','N','N');
Insert into pai_ref_insee_pays (CODE,PAYS,CAPITAL,NATIONALITE,ISO2,ISO3,UE_,EEE_) values ('310','ZIMBABWE',null,null,'ZW','ZWE','N','N');
